### ISSUE TITLE
Suggestion: Convert from coffeescript to Typescript or ES6 for additional community involvement

### ISSUE THREAD

**Issue by ajbogh** [kyriesent/node-rtsp-stream#19]
There are a ton of Javascript developers in the NodeJS and frontend world that would support a project like this. Coffeescript can be confusing to use when compared to regular JS. Not only is it an entirely different syntax, it doesn't even use the same variables (`@` instead of `this`). It's also a rarely used language in professional environments, as most people are migrating toward Typescript for strongly typed languages.

Suggestion: 
- Convert coffee files to ts
- Remove `/lib` from github, as that is a compiled folder that should only be published to npm
- Convert tests to js or ts files.
- Update package.json to compile ts to js for packaging and testing

I'm creating this issue now, with the hopes that I can offer a PR later (a sort of TODO). I'd be happy if someone can take it.

Reference comment in PR https://github.com/kyriesent/node-rtsp-stream/pull/16#issuecomment-441404930

**Comment by kyriesent** [comment]
@ajbogh I'm happy moving this over to JS now. When I started this project ES6 wasn't out the gate yet, but with the improvements they've made to scoping and async handling it's probably about time to move this over.

My only concern with TypeScript is that, like all transpiled languages, it may suffer a similar fate to CoffeeScript in a few years, and if we're going to make the move I'd rather only make it once. I also don't have any current experience in it, so that's a thing.

I understand that either move would be a lot of work, and I'm not currently in a position to put it in. That being said, I'm impressed with how much work you've already put into this, and I'm very thankful for that. If you are interested in making a language change PR, let me know before you get started so that we can talk about it!

**Comment by ajbogh** [comment]
I'll look into addressing this after #20 gets merged.

**Comment by kyriesent** [comment]
Finally moved the codebase over to vanilla JS. Closing.
