### ISSUE TITLE
Stopped after 2-3 minutes

### ISSUE THREAD

**Issue by harsh10c** [kyriesent/node-rtsp-stream#7]
I am able to rtsp stream (from IP Camera), but it stopped after approx. 2-3 minutes after displaying 
this errorlines.

frame= 4164 fps= 29 q=11.8 size=   13929kB time=00:02:18.73 bitrate= 822.5kbits/
[h264 @ 00000000021f00a0] error while decoding MB 78 26, bytestream -5
[h264 @ 00000000021f00a0] concealing 1491 DC, 1491 AC, 1491 MV errors in I frame

frame= 4184 fps= 28 q=13.0 size=   14001kB time=00:02:19.40 bitrate= 822.8kbits/
frame= 4190 fps= 28 q=12.2 Lsize=   14036kB time=00:02:19.63 bitrate= 823.4kbits/s dup=2094 drop=5 speed=0.941x
video:14036kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

**Comment by kyriesent** [comment]
Error output doesn't seem especially clear so I'm not sure if I can help very much. Does this error happen every time you try to stream after 2-3 minutes? An `error while decoding` sounds like a corrupted data stream, but I can't know for sure. FFMPEG forums might be a better place to figure out what that error might mean.

As for this library, you might want to check for errors on the spawned child process, and reattach to the stream with a new child process, so that even though you might lose a few frames, you could recover from the error and pick it back up.

**Comment by harsh10c** [comment]
Sorry for late reply.

Issue was due to network speed.

However, still after 1 or 2 hour , it breaks streaming even in excellent network speed.

**Comment by kyriesent** [comment]
Thanks for letting me know. Are you still getting the same error? Any output?

**Comment by kyriesent** [comment]
Stale issue, closing.
